---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lolla-kustomization
  namespace: flux-system
spec:
  interval: 30s
  path: ./files
  prune: true
  sourceRef:
    kind: ""
    name: ""
