---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ola-kustomization
  namespace: flux-system
spec:
  interval: 30s
  path: ./twins-art-project/files
  prune: true
  sourceRef:
    kind: GitRepository
    name: twins-art-project
  targetNamespace: flux-system
