apiVersion: v1
kind: Service
metadata:
  labels:
    app: twins-art-project
  name: twins-art-project
spec:
  ports:
  - nodePort: 30171
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: twins-art-project

  type: NodePort
